<?php

namespace App\ProcessRobot\cad_apolice\Classes\Vars;


/**
 * Classe com variáveis padrões do Automóvel para o Quiver
 */

class QuiverAutomovelVar{
    
    /**
     * Lista de fabricantes. Sintaxe: cod=>fab ou cod=>[fab1a,fab1b] (quer dizer que tem dois nomes de fabricantes para o mesmo código)
     */
    public static $fabricante_code=[
            "2465"=>"MAN",
            "2283"=>"VOLKSWAGEN",
            "2491"=>"37 0360",
            "2434"=>"ACCELO",
            "70"=>"ACURA",
            "2387"=>"ADLY",
            "1"=>"AGRALE",
            "1622"=>"AKERMAN",
            "993"=>"ALDEE",
            "2378"=>"ALFA",
            "2"=>"ALFA ROMEO",
            "91"=>"AM GENERAL",
            "2354"=>"AMAZONAS",
            "153"=>"ANTONINI",
            "93"=>"APRILIA",
            "3"=>"ASIA",
            "2367"=>"ASTON",
            "98"=>"ATALA",
            "2341"=>"ATEGO",
            "2173"=>"ATRUDI",
            "4"=>"AUDI",
            "2493"=>"AUTO MOBILE",
            "994"=>"AVALLONE",
            "2369"=>"BENELLI",
            "5"=>"BENTLEY",
            "2399"=>"BETA",
            "995"=>"BIANCO",
            "1967"=>"BIMOTA",
            "1018"=>"BITREM",
            "6"=>"BMW",
            "7"=>"BRANDY",
            "2359"=>"BRAVA",
            "87"=>"BRM",
            "1953"=>"BRP",
            "2372"=>"BUELL",
            "2390"=>"BUENO",
            "991"=>"BUGGY",
            "2364"=>"BUGRE",
            "1187"=>"BUSSCAR",
            "2401"=>"BYCRISTO",
            "73"=>"CADILLAC",
            "71"=>"CAGIVA",
            "1826"=>"CAIO",
            "68"=>"CALOI",
            "58"=>"CBT",
            "996"=>"CHAMONIX",
            "1080"=>"CHANA",
            "1444"=>"CHANGAN",
            "2494"=>"CHE S10 PICK-UP LUXE 2.8 4X2",
            "1038"=>"CHEDA",
            "1081"=>["CHERY","CAOA CHERY"],
            "17"=>"CHEVROLET",
            "1374"=>"CHITUMA",
            "9"=>"CHRYSLER",
            "2383"=>"CICCOBUS",
            "10"=>"CITROEN",
            "1824"=>"COMIL",
            "998"=>"CONCORDE",
            "2480"=>"COOPER",
            "999"=>"CORONA",
            "2315"=>"CREVROLET",
            "2406"=>"CROSS",
            "1000"=>"CROSS LANDER",
            "1929"=>"CRYSLER",
            "60"=>"DAELIM",
            "11"=>"DAEWOO",
            "2180"=>"DAF",
            "1078"=>"DAFRA",
            "12"=>"DAIHATSU",
            "1306"=>"DAILY",
            "2386"=>"DAYANG",
            "1243"=>"DAYUN",
            "2131"=>"DCODGE",
            "2239"=>"DD",
            "2385"=>"DERBI",
            "13"=>"DODGE",
            "1919"=>"DOLLY",
            "2172"=>"DTOYOTA",
            "72"=>"DUCATI",
            "1077"=>"EFFA",
            "2366"=>"EFFA-JMC",
            "69"=>"EMME",
            "59"=>"ENGESA",
            "74"=>"ENVEMO",
            "1002"=>"ENVESA",
            "2421"=>"ESPECIAL",
            "2492"=>"FAB PROP",
            "1003"=>"FABRAL",
            "1991"=>"FABRICANTE NÃO ENCONTRADO",
            "148"=>"FACCHINI",
            "2324"=>"FACE",
            "2224"=>"FAOURD",
            "1004"=>"FARUS",
            "14"=>"FERRARI",
            "15"=>"FIAT",
            "2368"=>"FIBRAVAN",
            "2488"=>"FIET",
            "2108"=>"FIIRAET",
            "2024"=>"FITEC",
            "16"=>"FORD",
            "2045"=>"FOTON AUMARK",
            "2356"=>"FYM",
            "2000"=>["G M","GM"],
            "2362"=>"GARINNI",
            "2190"=>"GCD M",
            "2267"=>"GEC OMNOFLE",
            "1975"=>"GEELY",
            "2342"=>"GEEP",
            "75"=>"GEO",
            "1073"=>"GERAL",
            "1005"=>"GLASPAC",
            "2102"=>["G M CHEVROLET", "G M - CHEVROLET","GM CHEVROLET" ,"GM - CHEVROLET"],
            "2101"=>"GM PFM",
            "61"=>"GMC",
            "2141"=>"GPO M",
            "2335"=>"GRAND",
            "2384"=>"GREAT",
            "2360"=>"GREEN",
            "1079"=>"GRIMALDI",
            "2117"=>"GTD M",
            "1075"=>"GUERRA",
            "57"=>"GURGEL",
            "1083"=>"HAFEI",
            "1355"=>"HAFEI/EFFA",
            "2352"=>"HAOBAO",
            "2398"=>"HAOJUE",
            "18"=>["HARLEY-DAVIDSON","HARLEY DAVIDSON"],
            "2382"=>"HARTFORD",
            "2212"=>"HAUOTNDA",
            "2408"=>"HERO",
            "1006"=>"HOFSTETTER",
            "1194"=>"HOGGAR",
            "19"=>"HONDA",
            "2250"=>"HR",
            "1954"=>"HUMMER",
            "2161"=>"HUNDAY",
            "2377"=>"HUSABERG",
            "76"=>"HUSQVARNA",
            "20"=>"HYOSUNG",
            "21"=>"HYUNDAI",
            "1800"=>"IBIPORA",
            "1968"=>"IDEROL",
            "2158"=>"INDIAN",
            "2285"=>"INFINITI",
            "96"=>"INTERNATIONAL",
            "22"=>"ISUZU",
            "77"=>"IVECO",
            "2258"=>"IVECO-DAILY",
            "1084"=>"JAC MOTORS",
            "23"=>"JAGUAR",
            "78"=>"JEEP",
            "24"=>"JIALING",
            "2391"=>"JIAPENG",
            "2186"=>"JIMMY WIDE",
            "1360"=>"JINBEI",
            "2438"=>"JIPE",
            "2370"=>"JOHNNYPAG",
            "2374"=>"JONNY",
            "56"=>"JPX",
            "25"=>"KAHENA",
            "1703"=>"KARMAN-GHIA",
            "95"=>"KASINSKI",
            "26"=>["KAWASAKI","KAWAZAKI"],
            "27"=>["KIA MOTORS",'KIA'],
            "149"=>"KRONE",
            "8"=>"KTM",
            "2358"=>"KYMCO",
            "1039"=>"L AQUILA",
            "1044"=>"L AUTOMOBILE",
            "29"=>"LADA",
            "28"=>"LAFER",
            "30"=>"LAMBORGHINI",
            "31"=>"LAND ROVER",
            "2409"=>"LANDUM",
            "2363"=>"LAQUILA",
            "1012"=>"LASSALE",
            "2373"=>"LAVRALE",
            "1013"=>"LC-SABRE",
            "2361"=>"LERIVO",
            "79"=>"LEXUS",
            "2445"=>"LIBERTY",
            "1880"=>"LIBRELATO",
            "1085"=>"LIFAN",
            "97"=>"LINCOLN",
            "2310"=>"LINE",
            "2365"=>"LOBINI",
            "2397"=>"LON-V",
            "32"=>"LOTUS",
            "2156"=>"LS",
            "2495"=>"M PAJERO FULL GLS 3.2 4X4",
            "67"=>"MAFERSA",
            "2388"=>"MAGRÃO",
            "1117"=>"MAHINDRA",
            "2404"=>"MALAGUTI",
            "1283"=>"MAN",
            "90"=>"MARCOPOLO",
            "1286"=>"MASCARELLO",
            "33"=>"MASERATI",
            "1071"=>"MASSEY FERGUSON",
            "2312"=>"MASTER",
            "1014"=>"MATRA",
            "2389"=>"MAXIBUS",
            "34"=>"MAZDA",
            "2496"=>"MEGANE HATCH RXE",
            "35"=>["MERCEDES-BENZ","MERCEDES BENZ"],
            "80"=>"MERCURY",
            "2202"=>"MFIPAT",
            "2395"=>"MG",
            "2425"=>"MICHIGAN",
            "2323"=>"MIITSU",
            "1015"=>"MINI",
            "36"=>"MITSUBISHI",
            "81"=>"MIURA",
            "2393"=>"MIZA",
            "2219"=>"MODELO ESPECIAL",
            "2407"=>"MOTO",
            "99"=>"MOTO GUZZI",
            "2371"=>"MOTOCAR",
            "2350"=>"MOTORINO",
            "2403"=>"MRX",
            "2091"=>"MTITSUBISHI",
            "2070"=>"MULT",
            "1016"=>"MV AGUSTA",
            "124"=>"MVK",
            "92"=>"NAVISTAR",
            "1076"=>"NEW HOLLAND",
            "37"=>"NISSAN",
            "1338"=>"NOMA",
            "1274"=>"NOMA MOTORS",
            "2201"=>"OPEL",
            "89"=>"ORCA",
            "1258"=>"OUTROS",
            "2380"=>"PEGASSI",
            "38"=>"PEUGEOT",
            "2271"=>"PGO M",
            "50"=>"PIAGGIO",
            "2301"=>"PIPER AIRCRAFT",
            "82"=>"PLYMOUTH",
            "83"=>"PONTIAC",
            "39"=>"PORSCHE",
            "62"=>"PUMA",
            "64"=>"PUMA-ALFA METAIS",
            "1017"=>"RAGGE",
            "2026"=>"RAM",
            "142"=>"RANDON",
            "1955"=>"REBOCADOR",
            "1019"=>"REBOQUE",
            "2392"=>"REGAL",
            "1126"=>"RELY",
            "40"=>"RENAULT",
            "2357"=>"RIGUETE",
            "2096"=>"RN",
            "41"=>"ROLLS ROYCE",
            "42"=>"ROVER",
            "2351"=>"ROYAL",
            "2340"=>"RQ",
            "1361"=>"RUIYI",
            "43"=>"SAAB",
            "85"=>"SAAB-SCANIA",
            "2490"=>"SANGUIOMI",
            "100"=>"SANTA MATILDE",
            "54"=>"SANYANG",
            "84"=>"SATURN",
            "44"=>"SCANIA",
            "86"=>"SCANIA-VABIS",
            "45"=>"SEAT",
            "2265"=>"SEKAI",
            "2497"=>"SENTRA SL 2.0 FLEXSTART 16V AU",
            "1124"=>"SHINERAY",
            "2394"=>"SIAMOTO",
            "63"=>"SIMCA",
            "1151"=>"SINOTRUK",
            "101"=>"SMART",
            "2166"=>"SPORTLINESPORTS",
            "55"=>"SSANGYONG",
            "46"=>"SUBARU",
            "66"=>"SUNDOWN",
            "47"=>"SUZUKI",
            "2290"=>"TAC",
            "2379"=>"TARGOS",
            "1325"=>"TECTOR",
            "2182"=>"TGD M",
            "2402"=>"TIGER",
            "2489"=>"TIGUAM",
            "1021"=>"TOPAZZIO",
            "1277"=>"TOWN &amp; COUNTRY",
            "48"=>"TOYOTA",
            "2481"=>"TRAILLER",
            "125"=>"TRAXX",
            "49"=>["TRIUMPH","TRIUNPH"],
            "88"=>"TROLLER",
            "1072"=>"VALTRA",
            "2446"=>"VG",
            "2110"=>"VIVACERUA",
            "2233"=>"VM",
            "1074"=>"VOLARE",
            "51"=>"VOLKSWAGEM",
            "52"=>"VOLVO",
            "2165"=>"WAKE",
            "2353"=>"WALK",
            "2218"=>"WALTRA",
            "65"=>"WILLYS-OVERLAND",
            "2400"=>"WUYANG",
            "53"=>"YAMAHA",
            "2347"=>"ZAHER",
        ];
   
    /**
     * Retorna ao texto da var $fabricante_code()
     * Obs: esta função existe, pois na var $fabricante_code em alguns casos é retornado a um array
     */
    public static function getFabricante($code){
        foreach(self::$fabricante_code as $c=>$str){
            if($code==$c)return is_array($str) ? $str[0] : $str;
        }
        return '';
    }
    
    
   /**
    * Tipos de veículos
    */
    public static $tipos_code=[
        'a'=>'Automóvel',
        'm'=>'Moto',
        'c'=>'Caminhão',
    ];
    
    
   /**
    * Lista de combustíveis
    */
    public static $combustivel_code=[
        '1'	=>'Gasolina',
        '2'	=>'Álcool',
        '3'	=>'Diesel',
        '4'	=>'Gás',
        '5'	=>'Flex',
        '6'	=>'Álcool/Gás',
        '7'	=>'Gasolina/Álcool/Gás',
        '8'	=>'Gasolina/Gás',
        '9'	=>'Outros',
        '10'	=>'Elétrico',
        '11'	=>'TetraFuel',
    ];
}